### ISSUE TITLE
aeronmd gets stuck with two full proxy queues, and both agents trying to offer

### ISSUE THREAD

**Issue by reissGRVS** [aeron-io/aeron#1376]
Running in shared network mode it is possible to completely lock aeronmd. This seems to be due to both the receiver proxy command queue and the conductor proxy command queue being full, and both the conductor and receiver being stuck in a loop attempting to offer onto the opposite queue.

I reproduced this with a slightly modified version of BasicSubscriber, that opens 150 subscriptions instead of 1.

Process:
1. Start aeronmd with THREADING_MODE_SHARED_NETWORK
2. Start 150 publishers `seq 1001 1151  | xargs -n 1 -I{} -P 150 ./BasicPublisher -s {} > /dev/null`
3. Run the modified BasicSubscriber which opens subscriptions to all of the above stream ids
4. Stop BasicSubscriber
5. Repeat steps 3 and 4 until the driver keepalive times out consistently, for even a single subscriber or publisher.

I expect the same issue can be run into in all threading modes that use the proxy command queues.
```
(gdb) bt
#0  0x00007f43dab6b71b in sched_yield ()
#1  0x00007f43dacec7f9 in aeron_driver_receiver_proxy_offer (receiver_proxy=0x55afa3ef8eb0, cmd=0x55afa3fc7a30)
    ~/aeron/aeron-driver/src/main/c/aeron_driver_receiver_proxy.c:27
#2  0x00007f43daced2a2 in aeron_driver_receiver_proxy_on_remove_publication_image (receiver_proxy=0x55afa3ef8eb0, 
    image=0x55afa3f4d910)
    ~/aeron/aeron-driver/src/main/c/aeron_driver_receiver_proxy.c:388
#3  0x00007f43dacf9a40 in aeron_publication_image_on_time_event (conductor=0x55afa3ef7fb8, image=0x55afa3f4d910, 
    now_ns=3679428801108610, now_ms=1667385937553)
    ~/aeron/aeron-driver/src/main/c/aeron_publication_image.c:913
#4  0x00007f43dacd623e in aeron_publication_image_entry_on_time_event (conductor=0x55afa3ef7fb8, entry=0x55afa3f941d8, 
    now_ns=3679428801108610, now_ms=1667385937553)
    ~/aeron/aeron-driver/src/main/c/aeron_driver_conductor.c:1276
#5  0x00007f43dacd6d31 in aeron_driver_conductor_on_check_managed_resources (conductor=0x55afa3ef7fb8, 
    now_ns=3679428801108610, now_ms=1667385937553)
    ~/aeron/aeron-driver/src/main/c/aeron_driver_conductor.c:1414
#6  0x00007f43dacda859 in aeron_driver_conductor_do_work (clientd=0x55afa3ef7fb8)
    ~/aeron/aeron-driver/src/main/c/aeron_driver_conductor.c:2807
#7  0x00007f43dacaa282 in aeron_agent_do_work (runner=0x55afa3ef9928)
    ~/aeron/aeron-client/src/main/c/aeron_agent.h:102
#8  0x00007f43dacd2970 in aeron_driver_main_do_work (driver=0x55afa3ef7fb0)
    ~/aeron/aeron-driver/src/main/c/aeron_driver.c:1027
#9  0x000055afa3c18915 in main (argc=1, argv=0x7ffed0b89818)
    ~/aeron/aeron-driver/src/main/c/aeronmd.c:143
(gdb) thread 2
[Switching to thread 2 (Thread 0x7f43d9fc7700 (LWP 2966591))]
#0  0x00007f43dab6b71b in sched_yield () at ../sysdeps/unix/syscall-template.S:78
78      in ../sysdeps/unix/syscall-template.S
(gdb) bt
#0  0x00007f43dab6b71b in sched_yield ()
#1  0x00007f43dace0504 in aeron_driver_conductor_proxy_offer (conductor_proxy=0x55afa3ef80b0, cmd=0x55afa3f2b230)
    ~/aeron/aeron-driver/src/main/c/aeron_driver_conductor_proxy.c:27
#2  0x00007f43dace057c in aeron_driver_conductor_proxy_on_delete_cmd (conductor_proxy=0x55afa3ef80b0, cmd=0x55afa3f2b230)
    ~/aeron/aeron-driver/src/main/c/aeron_driver_conductor_proxy.c:43
#3  0x00007f43daceb029 in aeron_driver_receiver_on_command (clientd=0x55afa3ef8eb0, item=0x55afa3f2b230)
    ~/aeron/aeron-driver/src/main/c/aeron_driver_receiver.c:123
#4  0x00007f43daca0160 in aeron_spsc_concurrent_array_queue_drain (queue=0x55afa3ef6558, 
    func=0x7f43daceafab <aeron_driver_receiver_on_command>, clientd=0x55afa3ef8eb0, limit=2)
    ~/aeron/aeron-client/src/main/c/concurrent/aeron_spsc_concurrent_array_queue.h:122
#5  0x00007f43daceb11d in aeron_driver_receiver_do_work (clientd=0x55afa3ef8eb0)
    ~/aeron/aeron-driver/src/main/c/aeron_driver_receiver.c:139
#6  0x00007f43dacd1ee3 in aeron_driver_shared_network_do_work (clientd=0x55afa3ef7fb0)
    ~/aeron/aeron-driver/src/main/c/aeron_driver.c:721
#7  0x00007f43dacaada5 in agent_main (arg=0x55afa3ef9978)
    ~/aeron/aeron-client/src/main/c/aeron_agent.c:407
#8  0x00007f43da8d4609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#9  0x00007f43dab88133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

I reproduced this on latest master (566aae4e6f2c7ced0201a7d7fcf42188bc2978c6) as well as the 1.40.0 release. I haven't tried on older versions.

**Comment by mikeb01** [comment]
I manage to replicate this issue as well.  I've made some changes that should reduce the traffic on the internal queues (which are actually now ring buffers).  I haven't been able to replicate the issue with this change in place.  Retrying your test using the referenced PR would be useful feedback.

**Comment by reissGRVS** [comment]
Response is in-review https://github.com/real-logic/aeron/pull/1377#discussion_r1012677428. 
Summary is that I can't reproduce but I dont think the underlying issue is solved, just much harder to hit due to massively increased command capacity.
